config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
 get 'welcome/about'
  resources :trainers do
    member do
      post :create_comment
      delete :destroy_comment
    end
  end
  resources :programs do
      member do
      post :create_comment
      delete :destroy_comment
    end
  end
  resources :clients do
      member do
      post :create_comment
      delete :destroy_comment
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :program_clients
  has_many :programs, through: :program_clients
  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic:true
end

app/models/program.rb
class Program < ActiveRecord::Base
  validates :name, presence: true
  has_many :program_clients
  has_many :clients, through: :program_clients
  has_many :program_trainers
  has_many :trainers, through: :program_trainers
  has_many :comments, as: :commentable
  belongs_to :user
end

app/models/program_client.rb
class ProgramClient < ActiveRecord::Base


belongs_to :program
belongs_to :client
end

app/models/program_trainer.rb
class ProgramTrainer < ActiveRecord::Base
  
belongs_to :program
belongs_to :trainer

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  has_many :program_trainers
  has_many :programs, through: :program_trainers
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :programs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
    @programs = Program.all
    @trainers = Trainer.all
  end
# def index
#   @programs = Program.all
# end

  def show
    @client = Client.find params[:id]
    @programs = @client.programs
    @programs = Program.all
    @trainers = Trainer.all
    @comment = Comment.new
  end

  def new
    @client = Client.new
    @programs = Program.all

  end

  def edit
    @client = Client.find params[:id]
    @programs = Program.all
  end

  def create
    @client = Client.create client_params
    if @client.save
      flash[:notice] = 'Client was successfully created.'
      redirect_to clients_path
    else
      flash[:error] = 'Client was NOT saved.'
      render :new
    end
  end

  def create_comment
    @client = Client.find params[:id]
    @comment = @client.comments.create comment_params
    redirect_to client_path(@client)
  end


  def update
    @client = Client.find params[:id] 
      if @client.update_attributes client_params
      redirect_to client_path(@client)
    else 
      render :new
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.delete
    redirect_to clients_path
  end

  def destroy_comment
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to @comment.commentable
  end

  def client_params
    params.require(:client).permit(
      :first_name,
      :last_name,
      :date_of_birth,
      :goals,
      program_id: []
    )
  end

  def comment_params
    params.require(:comment).permit(
      :content
      )

  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!

  def index
    @programs = Program.all
  end

  def new
    @program = Program.new
    @clients = Client.all
    @trainers = Trainer.all
    # @client = @program.clients.find params[:client_id]
    # @program = Program.find params[:program_id]
    # @client = Client.find params[:client_id]
  end

  def create
    @program = Program.create program_params
    @clients = Client.all
    @trainers = Trainer.all
    @program.user = current_user
    if @program.save
      flash[:notice] = "#{@program.name} information successsfully saved."
      redirect_to programs_path
    else
      flash[:error] = 'Program NOT successfully saved.'
      render :new
    end
  end

  def create_comment
    @program = Program.find params[:id]
    @comment = @program.comments.create comment_params
    redirect_to program_path(@program)
  end


  def show
    @program = Program.find params[:id]
    @clients = @program.clients
    @trainers = @program.trainers
    @comment = Comment.new
  end

  def edit
    @program = Program.find params[:id]
    @clients = Client.all
    @trainers = Trainer.all
  end

  def update
    @clients = Client.all 
    @trainers = Trainer.all
    @program = Program.find params[:id]
    @program.user = current_user
    if @program.update program_params
      flash[:notice] = "#{@program.name} information successfully updated."
      redirect_to program_path(@program)
    else
      flash[:error] = 'Program NOT successfully updated.'
      render :new
    end
  end

  def destroy
    @program = Program.find params[:id]
    @program.delete
    flash[:notice] = "#{@program.name} successfully deleted."
    redirect_to programs_path
  end

  def destroy_comment
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to @comment.commentable
  end

  private

  def program_params
    params.require(:program).permit(
      :name,
      :description,
      client_ids: [],
      trainer_ids: []
      )
  end

  def comment_params
    params.require(:comment).permit(
      :content
      )
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController

def index
  @trainers = Trainer.all
end 

def new
  @trainer = Trainer.new
  @programs = Program.all


end 

def create
  @trainer = Trainer.create trainer_params
  redirect_to trainers_path
end 

def create_comment
  @trainer = Trainer.find params[:id]
  @comment = @trainer.comments.create comment_params
  redirect_to trainer_path(@trainer)
end

def edit
  @trainer = Trainer.find params[:id]
  @programs = Program.all
end

def update
  @trainer = Trainer.find params[:id]
  @trainer.update_attributes trainer_params
  redirect_to trainer_path(@trainer)
end 

def show
  @trainer = Trainer.find params[:id]
  @programs = @trainer.programs
  @comment = Comment.new
end 
def destroy
  @trainer = Trainer.find params[:id]
  @trainer.delete
  redirect_to trainers_path
end

def destroy_comment
  @comment = Comment.find params[:id]
  @comment.destroy
  redirect_to @comment.commentable
end

private
def trainer_params
  params.require(:trainer).permit(
    :first_name,
    :last_name,
    :about_me,
    program_ids: []
    )

end

def comment_params
  params.require(:comment).permit(
    :content
    )
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link(path)
    :active if current_page?(path) == path
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.haml
-@client.inspect
= form_for [@client] do |f|
  -if @client.errors.any?
    - @client.errors.full_messages.each do |message|
      =message
      %br
=form_for @client do |f|
  =f.label :first_name
  =f.text_field :first_name
  %br
  =f.label :last_name
  =f.text_field :last_name
  %br
  =f.label :date_of_birth
  =f.date_field :date_of_birth
  %br
  =f.label :goals
  =f.text_area :goals
  %br
  %br
  Name of Program:
  %br
  %br
  - @programs.each do |program|
    = check_box_tag 'client[program_ids][]', program.id, @client.programs.include?(program)
    =program.name
  %br
  =f.submit
  |
  = link_to "Cancel", root_path

app/views/clients/edit.html.haml
%h1 Edit Client
= render 'form'

app/views/clients/index.html.haml
.div
.col-md-4
  = link_to "Welcome", root_path
  |
  = link_to "Add Client", new_client_path(@client)
  |
  =link_to "Back", root_path
 
  .row 
    %center
      %h1 Client List

  -@clients.each do |client|
    %center
      %strong
        =link_to client.first_name, client_path(client)
        =link_to client.last_name, client_path(client)
    %center
      %strong 
      =client.date_of_birth.strftime("%m/%d/%Y")
    %br
      %strong Goals:
      =client.goals
      %br
      =link_to "Edit", edit_client_path(client)
      |
      =link_to "Delete", client_path(client), method: :delete
.col-md-4
  %br
  %center 
    %h1 Programs Offered:
    - @programs.each do |program|
      %center
        %strong
        = link_to program.name, program_path(program)
.col-md-4
  %br
  %center 
    %h1 Trainers:
    - @trainers.each do |trainer|
      %center
        %strong
        =link_to trainer.first_name, trainer_path(trainer)
        =link_to trainer.last_name, trainer_path(trainer)
  

  

app/views/clients/new.html.haml
%h1 New Client
= render 'form'
= link_to 'Back', clients_path

app/views/clients/show.html.haml
%h2
= link_to "Welcome", root_path
.col-md-12
  %img{ :src => "/assets/workout.jpg" }

.col-md-4  
  %stong
  %h3
    = @client.first_name + @client.last_name
  %strong 
    = @client.date_of_birth.strftime("%m/%d/%Y")
  %br
  %strong
  %h3
    Goals:
    %h4
      = @client.goals
  %br
  =link_to "Delete Client", client_path(@client), method: :delete
  |
  = link_to 'Back', clients_path

%div 

.col-md-4
  %br
  %center 
    %h3 Programs Offered:
    - @programs.each do |program|
      %center
        %strong
          = link_to program.name, program_path(program)

.col-md-4
  %br
  %center  
    %h3 Trainers
    - @trainers.each do |trainer|
      %center
        %strong
          =link_to trainer.first_name, trainer_path(trainer)
          =link_to trainer.last_name, trainer_path(trainer)

.row
  .col-md-12
    %br
    %br
    .col-md-4.col-md-offset-5
      Internal Comments Concerning Client:
      %br
      - @client.comments.each do |comment|
        = comment.content
        = link_to "Delete Comment", destroy_comment_client_path(comment), method: :delete
        %br
      %br
      %br
      Add a New Comment:
      = form_for @comment, url: create_comment_client_path(@client) do |f|
        = f.label :content
        = f.text_area :content
        %br
        = f.submit


  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Team4
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    / Static navbar
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} KickAss Gym Management System
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Home", root_path
        %li
          = link_to "About", welcome_about_path
        %li
          %a{:href => "mailto: kickassgym@kickassgym.com?subject=Employee Input", :target => "_blank"} Contact
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Navigate
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to "Programs", programs_path
            %li
              = link_to "Trainers", trainers_path
            %li
              = link_to "Clients", clients_path
            / %li.divider
            / %li.dropdown-header Nav header
            / %li
            /   %a{:href => "#"} Separated link
            / %li
            /   %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li
            = link_to "Logout: #{current_user.email}", destroy_user_session_path, method: :delete 
        -else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path
    / /.nav-collapse
- if notice || alert
  %p.notice= notice
  %p.alert= alert
.container
  / Main component for a primary marketing message or call to action
  / .jumbotron
  /   %h1 KickAss Gym Management System
  /   .center-block
  /     - if current_user
  /       = "Gym Workout Programs Management Page"
  /     - else
  /       = "Welcome to the KickAss Gym Management System.  Please sign in above."
  /   %p
/ /container
/
  Bootstrap core JavaScript
  \==================================================
/ Placed at the end of the document so the pages load faster
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
= yield

app/views/programs/_form.html.haml
=form_for(@program) do |f|
  - if @program.errors.any?
    - @program.errors.full_messages.each do |message|
      = message
= form_for @program do |f|
  .form-group
    .list-group-item
      = f.label :name
      = ':'
      = f.text_field :name, class: "form-control"
      %br
      .form-group
        = f.label :description
        = ':'
        = f.text_area :description, class: "form-control"
  .list-group-item
    %strong
      Add Clients to Program:
      %br
    .checkbox
      - @clients.each do |client|
        %label
          = check_box_tag 'program[client_ids][]', client.id, @program.clients.include?(client)
          = client.first_name + ' ' + client.last_name
        %br
  %br
  .list-group-item
    %strong
      Add Trainers Who Offer Program:
      %br
    .checkbox
      - @trainers.each do |trainer|
        %label
          = check_box_tag 'program[trainer_ids][]', trainer.id, @program.trainers.include?(trainer)
          = trainer.first_name + ' ' + trainer.last_name
        %br
  %br
  .col-md-1.col-md-offset-4
  =f.submit "Submit", class: "btn btn-primary"

app/views/programs/_jumbotron.html.haml
.col-md-6.col-md-offset-3  
  .jumbotron-programs
    .text-center
      %h2

app/views/programs/edit.html.haml
.col-md-6.col-md-offset-3 
  .jumbotron-programs
    .text-center
      %h2
        Edit Program
      =link_to "Cancel", program_path(@program)
%br
.row
  .col-md-6.col-md-offset-3
    =render 'form'
%br

app/views/programs/index.html.haml
.col-md-6.col-md-offset-3
  .jumbotron-programs
    .text-center
      %h2
        Programs Offered
        %br
      = link_to "Add a Program", new_program_path
- @programs.each do |program|
  .col-md-4
    .list-group-item
      .text-center
        = link_to program.name, program_path(program)
        %br
        = link_to "Edit Program", edit_program_path(program)
        |
        = link_to "Delete Program", program_path(program), method: :delete
        %br
        %br

app/views/programs/new.html.haml
.col-md-6.col-md-offset-3  
  .jumbotron-programs
    .text-center
      %h2
        Add a New Workout Program
      = link_to "Cancel", programs_path
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    %br
    %br

app/views/programs/show.html.haml
.col-md-6.col-md-offset-3  
  .jumbotron-programs
    .text-center
      %h2
        Program Information
      = link_to "Back to Programs", programs_path
      %br
      = link_to "Edit", edit_program_path(@program)
      |
      = link_to "Delete", program_path(@program), method: :delete
      %br
      Last updated by:
      = @program.user.email
.row
  .col-md-6.col-md-offset-3
    .list-group-item
      .text-center
        %strong
          Program Name: 
        = @program.name
        %br
        %strong
          Description:
        = @program.description
        %br
    %br
    .list-group-item
      .text-center
        %strong
          Trainers Who Teach:
          %br
        - @trainers.each do |trainer|
          = trainer.first_name + ' ' + trainer.last_name
          %br
    %br
    .list-group-item
      .text-center
        %strong
          Clients Taking Program:
          %br
        - @clients.each do |client|
          = client.first_name + ' ' + client.last_name
          %br
    %br
    .list-group-item
      %strong
        .text-center
          Internal Program Comments:
      %ul
        - @program.comments.each do |comment|
          %li
            = comment.content
            |
            =link_to "Delete Comment", destroy_comment_program_path(comment), method: :delete
      %br
      = form_for @comment, url: create_comment_program_path(@program) do |f|
        .form-group
          .text-center
            = f.label :content, "Add Comment:"
          = f.text_area :content, class: "form-control"
          %br
          .text-center
            = f.submit "Submit Comment", class: "btn btn-primary"

      

app/views/trainers/_form.html.haml
=  form_for @trainer do |t|
  = t.label :first_name 
  = t.text_field :first_name 
  %br
  = t.label :last_name 
  = t.text_field :last_name
  %br
  = t.label :about_me
  = t.text_field :about_me 
  %br
  %h4
    Programs Taught:
  %br
  %br
  - @programs.each do |program| 
    .col-xs-4
      = check_box_tag 'trainer[program_ids][]', program.id, @trainer.programs.include?(program)
      = program.name
  = t.submit 
  %br
  %br 





   

app/views/trainers/_navbar.html.haml
/ Static navbar
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} KickAss Gym Management System
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to "Home", root_path
        %li
          %a{:href => "#about"} About
        %li
          %a{:href => "#contact"} Contact
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to "Programs", programs_path
            %li
              = link_to "Trainers", trainers_path
            %li
              = link_to "Clients", clients_path
            / %li.divider
            / %li.dropdown-header Nav header
            / %li
            /   %a{:href => "#"} Separated link
            / %li
            /   %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li
            = link_to "Logout: #{current_user.email}", destroy_user_session_path, method: :delete 
        -else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path
    / /.nav-collapse
- if notice || alert
  %p.notice= notice
  %p.alert= alert
.container
  / Main component for a primary marketing message or call to action
  .jumbotron
    %h1 KickAss Gym Management System
    - if current_user
      = "Gym Trainers Management Page"
    - else
      = "Welcome to the KickAss Gym Management System.  Please sign in above."
    %p
/ /container
/
  Bootstrap core JavaScript
  \==================================================
/ Placed at the end of the document so the pages load faster
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
%script{:src => "../../dist/js/bootstrap.min.js"}
/ IE10 viewport hack for Surface/desktop Windows 8 bug
%script{:src => "../../assets/js/ie10-viewport-bug-workaround.js"}

app/views/trainers/edit.html.haml
/ =link_to "Home", root_path
%br
=link_to "Back", trainers_path
%br
%br

= render 'form'

app/views/trainers/index.html.haml
%h1
  .text-center
    ="Trainers"
/ %h6
/   =link_to "Home", root_path
/ =link_to :back
%br
%h4
  =link_to "Add New Trainer", new_trainer_path

%br

- @trainers.each do |trainer|
  .col-xs-4
    %h5
      =link_to trainer.first_name, trainer_path(trainer)
      =link_to trainer.last_name, trainer_path(trainer)
  
  


  

app/views/trainers/new.html.haml
/ =link_to "Home", root_path
%br
%br
=link_to "Back", trainers_path
%br
%br

=render 'form'

app/views/trainers/show.html.haml
/ =link_to "Home", root_path

=link_to "Back", trainers_path
%br 
=link_to "Edit", edit_trainer_path
%br
=link_to "Delete", trainer_path, method: :delete
%br
%br
%h2
  .text-center 
    TRAINER
%brf
%br
%h5
  First Name: 
= @trainer.first_name
%br
%h5
  Last Name:
= @trainer.last_name
%br
%h5
  About Me:
= @trainer.about_me
%br
I teach the following programs:
-@programs.each do |program|
  = program.name
%br
%br
%strong
  Internal comments concerning trainer:
  %br
-@trainer.comments.each do |comment|
  = comment.content
  = link_to "Delete Comment", destroy_comment_trainer_path(comment), method: :delete
  %br
%br
= form_for @comment, url: create_comment_trainer_path(@trainer) do |f|
  = f.label :content
  = f.text_area :content
  %br
  = f.submit

app/views/welcome/about.html.haml
We are a pretty kick ass gym.  We like to keep our clients, workout programs, and trainers information in one awesome system.

app/views/welcome/index.html.haml
.col-md-6.col-md-offset-3
  .jumbotron
    .text-center
      %h4
        - if current_user
          = "Welcome to the KickAss Gym Management System"
          %br
          = "You are signed in as #{current_user.email}"
        -else
          = "Welcome to the KickAss Gym Management System"
          %br
          = "Please login"